name: "Upload Artifact"
description: "Unified artifact upload for Peer Network CI"

inputs:
  name:
    description: "Artifact name"
    required: true
  path:
    description: "Path to upload"
    required: true
  if_no_files_found:
    description: "Behavior when file is missing (warn, error, ignore)"
    required: false
    default: "warn"

runs:
  using: "composite"
  steps:
    - name: Upload artifact using v5
      uses: actions/upload-artifact@v5
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
        if-no-files-found: ${{ inputs.if_no_files_found }}
